// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbheDZ-bd4_J_A_Dn0M5u8npgZaLjDob0',
    appId: '1:241285456952:web:c3aa313297d6db58f4f2cd',
    messagingSenderId: '241285456952',
    projectId: 'data-center-proejcts',
    authDomain: 'data-center-proejcts.firebaseapp.com',
    storageBucket: 'data-center-proejcts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvM45AdAWFec9IPqV5LI8XIZyejhGAwE',
    appId: '1:241285456952:android:cbb9dc728aa71a2df4f2cd',
    messagingSenderId: '241285456952',
    projectId: 'data-center-proejcts',
    storageBucket: 'data-center-proejcts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFxLWdfKFMWUJsfSwEJLMrBhmazd5ijo',
    appId: '1:241285456952:ios:26d20767ccaf92def4f2cd',
    messagingSenderId: '241285456952',
    projectId: 'data-center-proejcts',
    storageBucket: 'data-center-proejcts.appspot.com',
    iosClientId: '241285456952-66sgrc0lg1ojvfidh5ivs97tnv6t2ngv.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataCenterProjects',
  );
}
